name: Run Test
on:
  push:
    branches: main
  pull_request:
    branches: main,dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml 
      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: dart analyze

#      - name: Run tests
#        run: flutter test
